name: Call workflow

on:
  push:

jobs:
  main:
    if: false
    uses: ./.github/workflows/reusable.yaml
    
  results:
    name: results
    runs-on: ubuntu-latest
    needs:
      - main
    steps:
      - name: results
        run: |
          echo "the result of job is ${{ needs.main.result }}"
          echo "the result of step in the job is ${{ needs.main.outputs.mars || 'skipped' }}"
