name: Call workflow

on:
  push:

jobs:
  main:
    name: main job
    uses: ./.github/workflows/reusable.yaml
    with:
      experimental: false

  test:
    name: test job
    uses: ./.github/workflows/reusable.yaml
    with:
      experimental: true

  outputs:
    name: Cat outputs
    runs-on: ubuntu-latest
    needs:
      - main
      - test
    if: always()
    steps:
      - name: Display main output
        run: |
          echo "world output is ${{ needs.main.outputs.world-output }} and mars output is ${{ needs.main.outputs.mars-output }}"
          echo "main output is ${{ needs.main.outputs.job-result }}"
          echo "main result is ${{ needs.main.result }}"

      - name: Display test output
        run: |
          echo "world output is ${{ needs.test.outputs.world-output }} and mars output is ${{ needs.test.outputs.mars-output }}"
          echo "test output is ${{ needs.test.outputs.job-result }}"
          echo "test result is ${{ needs.test.result }}"