name: Reusable workflow

on:
  workflow_call:

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Hello world
        id: world
        run: |
          echo "hello world"
      - name: Hello mars
        id: mars
        run: |
          echo "hello mars"
          exit 1
