name: Reusable workflow

on:
  workflow_call:
    outputs:
      mars:
        value: ${{ jobs.job1.outputs.outcome }}

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.mars.outcome }}
    steps:
      - name: Hello world
        id: world
        run: |
          echo "hello world"
      - name: Hello mars
        id: mars
        continue-on-error: true
        run: |
          echo "hello mars"
          exit 1
