name: Reusable workflow

on:
  workflow_call:

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        id: world
        run: |
          echo "hello world"
      - name: Hello mars
        continue-on-error: true
        id: mars
        run: |
          echo "hello mars"
          exit 1
  job2:
    name: Second job
    runs-on: ubuntu-latest
    steps:
      - name: Hello Saturn
        run: |
          echo "Hello saturn"
